#
# Class of src/commands/ using this config
#
command-class: pagetoc

#
# Command parameters
#
tags: [h2, h3]
file: test.html
exclude:
    - z.*
insert-after: <article>
#action: save
action: print-toc
