#
# Class of src/commands/ using this config
#
command-class: replaceHtml

#
# Command parameters
#
before: '<footer>'
after: '</footer>'
replacement-file: static/html/footer.html
#exclude:
#  - index.html