#
# Command to replace the right sidebar
# Uses the page configuration 'sidebar-right' directive
#
command-class: replaceHtml
before: '<aside class="sidebar-right">'
after: '</aside>'
replacement-directive: sidebar-right
exclude:
  - maths/categories/milewski-youtube-notes/*