#
# Executed only once
#

#
# Class of src/commands/ using this config
#
command-class: insertHtml

#
# Command parameters
#
after: '<body>'
insert-string: |
  
  <div class="container">
  
  <div class="main">
exclude:
  - index.html