#
# Executed only once
#

#
# Class of src/commands/ using this config
#
command-class: insertHtml

#
# Command parameters
#
after: '</article>'
insert-string: |
  
  </div><!-- end class="main" -->
exclude:
  - index.html