#
# Executed only once
#

#
# Class of src/commands/ using this config
#
command-class: insertHtml

#
# Command parameters
#
before: '</body>'
insert-string: |
  <footer class="footer">
  </footer>
exclude:
  - index.html