
#
# Executed only once
#
command-class: insertHtml
before: '<footer>'
insert-string: |
  
  <!-- ************************************* -->
  <aside class="right">
  </aside>
  
  </div><!-- end class="container" -->
  
  <!-- ************************************* -->
exclude:
  - index.html